name: 🔎 Code Quality

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  linter:
    name: 🧹 Linter
    if: github.event.pull_request.draft == false
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Run oxlint
        run: pnpm oxlint --deny-warnings .

  typescriptChecker:
    name: 🟦 TypeScript Checker
    if: github.event.pull_request.draft == false
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: 24

      - name: Run Typescript checker
        run: pnpm run lint:ts
